const IS_FETCHING = 'IS_FETCHING';
const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
const SET_BOOKS = 'SET_BOOKS';
const SET_BOOK_DETAILS = 'SET_BOOK_DETAILS';

export {
    IS_FETCHING,
    SET_SEARCH_TEXT,
    SET_BOOKS,
    SET_BOOK_DETAILS,
};